# py-nvfan
# This is a configuration file for the fan control system.

# temps
# The target temperatures are the temperatures at which the fan should operate.
temps:
  - 30
  - 50
  - 70
  - 80
  - 100

# targetDuties
# The duty cycle is the percentage of time the fan is on in a given period.
fanSpeeds:
  - 30
  - 50
  - 70
  - 80
  - 100
